name: eShopOnWeb Build and Test

on:
  workflow_dispatch:

env:
  RESOURCE_GROUP: rg-eshoponweb-westeurope
  LOCATION: westeurope
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: be12bac3-d70f-49ac-b802-1ed971da2364
  WEBAPP_NAME: devops-webapp-westeurope-55931093

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'

    - name: Restore dependencies
      run: dotnet restore ./eShopOnWeb.sln

    - name: Build solution
      run: dotnet build ./eShopOnWeb.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./eShopOnWeb.sln --configuration Release --no-build --verbosity minimal

    - name: Publish Web project
      run: |
        dotnet publish ./src/Web/Web.csproj --configuration Release --output ./publish
        cd ./publish
        zip -r ../app.zip .

    - name: Upload published app
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ./app.zip

    - name: Upload Bicep template
      uses: actions/upload-artifact@v4
      with:
        name: bicep-template
        path: ${{ env.TEMPLATE_FILE }}

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: Development
    steps:
    - name: Download published app
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: ./dotnet-app

    - name: Download Bicep template
      uses: actions/download-artifact@v4
      with:
        name: bicep-template
        path: ./bicep-template

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy infrastructure with Bicep
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: ./bicep-template/webapp.bicep
        parameters: webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}
        failOnStdErr: false

    - name: Deploy Web App using Azure CLI
      uses: azure/cli@v2
      with:
        inlineScript: |
          az webapp deploy \
            --name ${{ env.WEBAPP_NAME }} \
            --resource-group ${{ env.RESOURCE_GROUP }} \
            --src-path ./dotnet-app/app.zip \
            --type zip
