name: eShopOnWeb Build and Test

on: [push, workflow_dispatch]

env:
  RESOURCE_GROUP: rg-eshoponweb-eastus2
  LOCATION: eastus2
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: be12bac3-d70f-49ac-b802-1ed971da2364
  WEBAPP_NAME: saithaeoodevops-webapp-eastus2-10272025

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release

    - name: Run Unit Tests
      run: dotnet test ./tests/UnitTests/UnitTests.csproj --configuration Release
      continue-on-error: true

    - name: Run Integration Tests
      run: dotnet test ./tests/IntegrationTests/IntegrationTests.csproj --configuration Release
      continue-on-error: true

    - name: dotnet publish
      run: |
        dotnet publish ./src/Web/Web.csproj -c Release -o ${{env.DOTNET_ROOT}}/myapp
        cd ${{env.DOTNET_ROOT}}/myapp
        zip -r ../app.zip .

    - name: Upload .NET app artifact
      uses: actions/upload-artifact@v4
      with:
        name: .net-app
        path: ${{env.DOTNET_ROOT}}/app.zip

    - name: Upload Bicep template artifact
      uses: actions/upload-artifact@v4
      with:
        name: bicep-template
        path: infra/webapp.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: buildandtest
    environment:
      name: 'Development'
    steps:
    - name: Download .NET app artifact
      uses: actions/download-artifact@v4
      with:
        name: .net-app
        path: .net-app

    - name: Download Bicep template artifact
      uses: actions/download-artifact@v4
      with:
        name: bicep-template
        path: bicep-template

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy Azure WebApp using Bicep
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ env.SUBSCRIPTION_ID }}
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        template: bicep-template/webapp.bicep
        parameters: 'webAppName=${{ env.WEBAPP_NAME }} location=${{ env.LOCATION }}'
        failOnStdErr: false

    - name: Publish Website to WebApp using CLI
      uses: Azure/cli@v2
      with:
        inlineScript: |
          az webapp deploy --name ${{ env.WEBAPP_NAME }} --resource-group ${{ env.RESOURCE_GROUP }} --src-path .net-app/app.zip --type zip
